export const GET_POKEMONS_START = "GET_POKEMONS_START";
export const GET_POKEMONS_ERROR = "GET_POKEMONS_ERROR";
export const GET_POKEMONS_COMPLETE = "GET_POKEMONS_COMPLETE";

export const GET_POKEMON_DATA_START = "GET_POKEMON_DATA_START";
export const GET_POKEMON_DATA_ERROR = "GET_POKEMON_DATA_ERROR";
export const GET_POKEMON_DATA_COMPLETE = "GET_POKEMON_DATA_COMPLETE";
