// Pokemon constants.

export const GET_POKEMONS_START = "GET_POKEMONS_START";
export const GET_POKEMONS_ERROR = "GET_POKEMONS_ERROR";
export const GET_POKEMONS_COMPLETE = "GET_POKEMONS_COMPLETE";

export const GET_POKEMON_DATA_START = "GET_POKEMON_DATA_START";
export const GET_POKEMON_DATA_ERROR = "GET_POKEMON_DATA_ERROR";
export const GET_POKEMON_DATA_COMPLETE = "GET_POKEMON_DATA_COMPLETE";

// Berries constants.

export const GET_BERRIES_START = "GET_BERRIES_START";
export const GET_BERRIES_ERROR = "GET_BERRIES_ERROR";
export const GET_BERRIES_COMPLETE = "GET_BERRIES_COMPLETE";

// Items constants.

export const GET_ITEMS_START = "GET_ITEMS_START";
export const GET_ITEMS_ERROR = "GET_ITEMS_ERROR";
export const GET_ITEMS_COMPLETE = "GET_ITEMS_COMPLETE";

export const GET_ITEM_BY_ID_START = "GET_ITEM_BY_ID_START";
export const GET_ITEM_BY_ID_ERROR = "GET_ITEM_BY_ID_ERROR";
export const GET_ITEM_BY_ID_COMPLETE = "GET_ITEM_BY_ID_COMPLETE";
